title: Jonathan Chung
email: jt2chung@edu.uwaterloo.ca
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://jonathanchung.xyz" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  chjon

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "home"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/